#!/usr/bin/python

import sys
import os

from PySide import QtGui

from pomolib import mainwidget
from pomolib import config

def main():

    app = QtGui.QApplication(sys.argv)

    window = mainwidget.MainWindow()
    window.show()
    window.center()

    icon = QtGui.QIcon(os.path.join(config.assets_dir, 'Tomato.png'))
    window.setWindowIcon(icon)
    window.setWindowIconText('Pomotimer')
    window.setWindowTitle('Pomotimer')

    return app.exec_()

if __name__ == "__main__":
    main()
